name: Build and deploy BulletinBoard.Api to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"

      - name: Restore API dependencies
        run: dotnet restore src/BulletinBoard.Api/BulletinBoard.Api.csproj

      - name: Build API
        run: dotnet build src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release

      - name: Publish API
        run: dotnet publish src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release -o ./myapp

      - name: Upload published API
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download published API
        uses: actions/download-artifact@v4
        with:
          name: api-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to MyApiApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "MyApiApp"
          slot-name: "Production"
          package: "./myapp"
