name: Build & deploy BulletinBoard.Api

on:
  push:
    branches: [ master ]
    paths:
      - 'src/BulletinBoard.Api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with: dotnet-version: '9.0'
      - name: Restore
        run: dotnet restore src/BulletinBoard.Api/BulletinBoard.Api.csproj
      - name: Build
        run: dotnet build src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release
      - name: Publish
        run: dotnet publish src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release -o ./myapp
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./myapp

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: name: api-artifact
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyApiApp'
          package: './myapp'
