name: Build & deploy BulletinBoard.Api

on:
  push:
    branches: [master]
    paths:
      - "src/BulletinBoard.Api/**"
  # ← allow one-click/manual runs from the Actions UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"

      - name: Restore
        run: dotnet restore src/BulletinBoard.Api/BulletinBoard.Api.csproj

      - name: Build
        run: dotnet build src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release

      - name: Publish
        run: dotnet publish src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release -o ./myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./myapp

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact into ./myapp
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: "./myapp"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (clean ZIP deploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "MyApiApp"
          package: "./myapp"
          remove-additional-files-flag: true
