name: Build and deploy BulletinBoard.Api to Azure Web App - MyApiApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Restore API dependencies
        run: dotnet restore src/BulletinBoard.Api/BulletinBoard.Api.csproj

      - name: Build API
        run: dotnet build src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release

      # Option A: proper multiline with no trailing spaces after each “\”
      - name: Publish API (multiline)
        run: |
          dotnet publish src/BulletinBoard.Api/BulletinBoard.Api.csproj \
            -c Release \
            -o ./myapp

      # Option B: single line (simplest)
      #- name: Publish API (single line)
      #  run: dotnet publish src/BulletinBoard.Api/BulletinBoard.Api.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read   # for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: api-artifact

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyApiApp'
          slot-name: 'Production'
          package: './myapp'
